import type { Locale } from '@/lib/i18n'

const copy = {
  en: {
    portal: 'Secure portal', signIn: 'Sign in', email: 'Email address', password: 'Password', forgot: 'Forgot your password?', requestLink: 'Send reset link', reset: 'Set a new password', dashboard: 'Workspace', signOut: 'Sign out', projects: 'Projects', documents: 'Documents', quotations: 'Quotations', comments: 'Updates & comments', library: 'Verified product library', newProject: 'New project request', title: 'Title', description: 'Description', create: 'Create', upload: 'Upload document', category: 'Category', chooseFile: 'Choose a PDF, image, Word or Excel file', addComment: 'Add comment', approve: 'Approve', reject: 'Reject', download: 'Download securely', noItems: 'Nothing here yet.', pending: 'Pending review', role: 'Access role', client: 'Client dashboard', supplier: 'Supplier dashboard', status: 'Status', total: 'Total', validUntil: 'Valid until', loading: 'Loading secure workspace…', verify: 'Verify email', verified: 'Email verified. You can now sign in.', backToSignIn: 'Back to sign in', genericReset: 'If the account is eligible, a reset link will be sent.', resetDone: 'Password updated. You can now sign in.', securityNote: 'Private documents are checked against your organization access on every download.', error: 'Something went wrong.', projectPrompt: 'Describe the project or delivery request.', commentPrompt: 'Share an update or question.', selectProject: 'Select a project', language: 'Language', passwordRules: 'Use 12–128 characters with upper-case, lower-case and a number.',
  },
  zh: {
    portal: '安全门户', signIn: '登录', email: '电子邮箱', password: '密码', forgot: '忘记密码？', requestLink: '发送重置链接', reset: '设置新密码', dashboard: '工作区', signOut: '退出登录', projects: '项目', documents: '文件', quotations: '报价', comments: '更新与评论', library: '已验证产品资料库', newProject: '新项目申请', title: '标题', description: '说明', create: '创建', upload: '上传文件', category: '类别', chooseFile: '选择 PDF、图片、Word 或 Excel 文件', addComment: '添加评论', approve: '批准', reject: '拒绝', download: '安全下载', noItems: '暂无内容。', pending: '等待审核', role: '访问角色', client: '客户控制台', supplier: '供应商控制台', status: '状态', total: '总额', validUntil: '有效期至', loading: '正在加载安全工作区…', verify: '验证邮箱', verified: '邮箱已验证。您现在可以登录。', backToSignIn: '返回登录', genericReset: '如果账户符合条件，我们将发送重置链接。', resetDone: '密码已更新。您现在可以登录。', securityNote: '每次下载私密文件时，系统都会核对您的组织访问权限。', error: '操作失败。', projectPrompt: '请说明项目或交付需求。', commentPrompt: '分享进展或问题。', selectProject: '选择项目', language: '语言', passwordRules: '使用 12–128 个字符，并包含大写字母、小写字母和数字。',
  },
  fr: {
    portal: 'Portail sécurisé', signIn: 'Se connecter', email: 'Adresse courriel', password: 'Mot de passe', forgot: 'Mot de passe oublié ?', requestLink: 'Envoyer le lien', reset: 'Définir un nouveau mot de passe', dashboard: 'Espace de travail', signOut: 'Se déconnecter', projects: 'Projets', documents: 'Documents', quotations: 'Devis', comments: 'Mises à jour et commentaires', library: 'Bibliothèque de produits vérifiés', newProject: 'Nouvelle demande de projet', title: 'Titre', description: 'Description', create: 'Créer', upload: 'Téléverser un document', category: 'Catégorie', chooseFile: 'Choisir un PDF, une image, un fichier Word ou Excel', addComment: 'Ajouter un commentaire', approve: 'Approuver', reject: 'Refuser', download: 'Télécharger de façon sécurisée', noItems: 'Aucun élément pour le moment.', pending: 'En attente de vérification', role: 'Rôle d’accès', client: 'Tableau de bord client', supplier: 'Tableau de bord fournisseur', status: 'Statut', total: 'Total', validUntil: 'Valide jusqu’au', loading: 'Chargement de l’espace sécurisé…', verify: 'Vérifier le courriel', verified: 'Courriel vérifié. Vous pouvez maintenant vous connecter.', backToSignIn: 'Retour à la connexion', genericReset: 'Si le compte est admissible, un lien de réinitialisation sera envoyé.', resetDone: 'Mot de passe mis à jour. Vous pouvez maintenant vous connecter.', securityNote: 'Chaque téléchargement privé est autorisé selon l’accès de votre organisation.', error: 'Une erreur est survenue.', projectPrompt: 'Décrivez le projet ou la demande de livraison.', commentPrompt: 'Partagez une mise à jour ou une question.', selectProject: 'Choisir un projet', language: 'Langue', passwordRules: 'Utilisez 12 à 128 caractères avec une majuscule, une minuscule et un chiffre.',
  },
} as const

export function portalCopy(locale: Locale) {
  return copy[locale]
}
